### ISSUE TITLE
failed on line 769

### ISSUE THREAD

**Issue by alekiv** [dickontoo/omxmotion#1]
Failing with error:
root@airasp02:/usr/src/omxmotion# ./omxmotion -b 50000 -d /mnt/camshare/omx -s 100 -o 5 -r 25 -t 10
OMX_Init() completed at 768.
OMX_GetHandle(&clk, CLKNAME, &ctx, &genevents) failed on line 769: 80001000

**Comment by dickontoo** [comment]
'-b 50000' is optimistic -- it's in Mb/s.  80001000 is insufficient resources -- what's your RAM split?  You'll need about 128MB for the GPU.

**Comment by alekiv** [comment]
> what's your RAM split?

128/128

After reboot it has started working.
What is safe bitrate for raspberry?
Is it possible to flip image?

**Comment by dickontoo** [comment]
I've had it working with 1-16.  Flipping isn't yet possible, but I believe it's a fairly trivial thing to add (there's a rotation parameter you can feed the camera, but I haven't tried it yet), and it's on the list of things to do when I have some time.  Feel free to add it.
